export const menu_foods = [
    {
        id: '1',
        name: 'Chicken Burger',
        cookTime: '10-20',
        price: 20000,
        favorite: false,
        origins: ['Italy'],
        stars: 4.5,
        imageUrl: 'food-1.jpg',
        tags: ['FastFood', 'Popular', 'Lunch'],
    },
    {
        id: '2',
        name: 'Cow Burger',
        cookTime: '15-30',
        price: 35000,
        favorite: true,
        origins: ['USA', 'middle east'],
        stars: 5,
        imageUrl: 'food-2.jpg',
        tags: ['FastFood', 'Lunch'],
    },
    {
        id: '3',
        name: 'Texas Burger',
        cookTime: '10-20',
        price: 49000,
        favorite: false,
        origins: ['Texas'],
        stars: 4.5,
        imageUrl: 'food-3.jpg',
        tags: ['FastFood', 'Lunch'],
    },
    {
        id: '4',
        name: 'Shrimp Burger',
        cookTime: '10-15',
        price: 30000,
        favorite: true,
        origins: ['USA', 'Asia'],
        stars: 4.5,
        imageUrl: 'food-4.jpg',
        tags: ['FastFood', 'Lunch'],
    },
    {
        id: '5',
        name: 'Trout Burger',
        cookTime: '10-15',
        price: 25000,
        favorite: false,
        origins: ['Germany', 'USA'],
        stars: 4.0,
        imageUrl: 'food-5.jpg',
        tags: ['FastFood', 'Best Seller'],
    },
    {
        id: '6',
        name: 'Egg Burger',
        cookTime: '10',
        price: 38000,
        favorite: false,
        origins: ['Asian', 'China'],
        stars: 4.5,
        imageUrl: 'food-6.jpg',
        tags: ['Fry'],
    },
];

export const menu_foods_tags = [
    { name: 'All', count: 6 },
    { name: 'FastFood', count: 5 },
    { name: 'Best Seller', count: 1 },
    { name: 'Lunch', count: 4 },
    { name: 'Popular', count: 1 },
    { name: 'Fry', count: 1 },
];